# Generated by Django 3.1.2 on 2021-05-14 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20210513_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pay_dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 13, 13, 48, 868012, tzinfo=utc), verbose_name='決済日'),
            preserve_default=False,
        ),
    ]
